version: 0.dev{build}

branches:
  only:
  - prototype

environment:
  PYTHON: C:\Python36-x64

install:
- ps: .\scripts\prepare-windows.ps1

build_script:
- cmd: "%PYTHON%\python.exe" -m PyInstaller QuickQR.spec

test: off

artifacts:
- path: dist/QuickQR.exe
  name: executable

deploy:
- provider: GitHub
  auth_token:
    secure: /EKNndrZyMpOV+i9D506f8nayosOYFlu+casyIY94gVLT/D8DKt10N4v0TVgecpp
  artifact: executable
  draft: false
  prerelease: false