os:
  - linux
language: python
python: '3.6'
sudo: required
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
    language: generic
cache:
  - pip
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash scripts/prepare-osx.sh; fi
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -r scripts/requirements.txt
script: pyinstall QuickQR.spec
branches:
  only:
  - prototype