os:
  - linux
language: python
python: '3.6'
sudo: required
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
    language: generic
cache:
  - pip
install:
  - pip install -r requirements.txt
  - pip install -r scripts/requirements.txt
script: pyinstall QuickQR.spec
branches:
  only:
  - prototype